# Generated by Django 4.1 on 2022-08-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_boxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='length',
            field=models.IntegerField(verbose_name='Length'),
        ),
    ]
