# Generated by Django 4.1 on 2022-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_alter_vehicle_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Box height'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='length',
            field=models.IntegerField(verbose_name='Box length'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='width',
            field=models.IntegerField(verbose_name='Box width'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Truck height'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='length',
            field=models.IntegerField(verbose_name='Truck length'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='width',
            field=models.IntegerField(verbose_name='Truck width'),
        ),
    ]
