# Generated by Django 4.1 on 2022-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_alter_boxes_height_alter_boxes_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='Box length')),
                ('width', models.IntegerField(verbose_name='Box width')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='Truck length')),
                ('width', models.IntegerField(verbose_name='Truck width')),
            ],
        ),
        migrations.DeleteModel(
            name='Boxes',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
